# Generated by Django 3.0.7 on 2020-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Tag'),
        ),
    ]
