# Generated by Django 3.0.7 on 2020-11-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='appSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='pypos', max_length=200, null=True)),
                ('phone', models.CharField(default='01303351768', max_length=200, null=True)),
                ('address', models.CharField(default='Dhaka,Bangladesh', max_length=200, null=True)),
                ('currency', models.CharField(default='৳', max_length=200, null=True)),
                ('invoice_terms', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
