# Generated by Django 3.0.7 on 2020-11-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201109_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appSettings',
            new_name='appConfig',
        ),
    ]
