# Generated by Django 3.0.7 on 2020-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201109_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
